FROM python:3.9-slim

WORKDIR /app

# install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy producer code
COPY transaction_producer.py .

# create data directory
RUN mkdir -p /app/data

CMD ["python", "transaction_producer.py"]