# Dockerfile.detector
FROM python:3.9-slim

WORKDIR /app


RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt

COPY fraud_detector.py .

RUN mkdir -p /app/models


EXPOSE 8000

CMD ["python", "fraud_detector.py"]